import type { Content } from "./schema";

const PLACEHOLDER_IMG = (id: number) =>
  `https://picsum.photos/seed/${id}/800/600`;

const LOREM =
  "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.";

/**
 * Demo/POC dummy data - client-only, no server or API.
 * Content from breakdown: real titles, topic/region facets, Lorem descriptions.
 * Filter-by-topic uses exact sub-facet names; regions use "North America" (not N. America).
 */
export const DUMMY_CONTENT: Content[] = [
  {
    id: 1,
    title: "RAF's Gladiator Support Contract with Boeing Defence UK Extended for Two Years",
    description: LOREM,
    category: "news",
    type: "article",
    date: "29 October 2025",
    tags: ["Training", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(1),
    url: "https://www.raf.mod.uk/news/articles/rafs-gladiator-support-contract-with-boeing-defence-uk-extended-for-two-years/",
    isFeatured: true,
    labelTag: "Main news",
  },
  {
    id: 2,
    title: "12 Squadron Deploy to the Gulf",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "15 January 2026",
    tags: ["International partnerships", "Middle East", "Europe", "Main news"],
    imageUrl: PLACEHOLDER_IMG(2),
    url: "https://www.raf.mod.uk/news/articles/12-squadron-deploy-to-the-gulf/",
    labelTag: "Main news",
  },
  {
    id: 3,
    title: "RAF Deploy to Nevada for Exercise Red Flag 2026",
    description: LOREM,
    category: "operations",
    type: "video",
    date: "10 January 2026",
    tags: ["Exercises", "Training", "North America", "Oceania", "Europe", "Main news"],
    imageUrl: PLACEHOLDER_IMG(3),
    url: "https://www.raf.mod.uk/news/articles/raf-deploy-to-nevada-for-exercise-red-flag-2026/",
    labelTag: "Main news",
  },
  {
    id: 4,
    title: "Royal Air Force Typhoons Lead NATO Allies in Key Operational Training",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "8 January 2026",
    tags: ["Exercises", "Training", "Europe", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(4),
    url: "https://www.raf.mod.uk/news/articles/royal-air-force-typhoons-lead-nato-allies-in-key-operational-training/",
    labelTag: "Main news",
  },
  {
    id: 5,
    title: "RAF New Year Honours 2026",
    description: LOREM,
    category: "news",
    type: "article",
    date: "2 January 2026",
    tags: ["Honours", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(5),
    url: "https://www.raf.mod.uk/news/articles/raf-new-year-honours-2026/",
    labelTag: "Main news",
  },
  {
    id: 6,
    title: "RAF Typhoon fleet strengthened in £205 million boost for British jobs",
    description: LOREM,
    category: "equipment",
    type: "article",
    date: "19 January 2026",
    tags: ["Aircraft", "QRA", "Europe", "Middle East", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(6),
    url: "https://www.raf.mod.uk/news/articles/raf-typhoon-fleet-strengthened-in-205-million-boost-for-british-jobs/",
    labelTag: "Main news",
  },
  {
    id: 7,
    title: "80th anniversary of D-Day marked at the British Normandy Memorial",
    description: LOREM,
    category: "news",
    type: "article",
    date: "6 June 2025",
    tags: ["D-Day", "Anniversaries", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(7),
    url: "https://www.raf.mod.uk/news/articles/80th-anniversary-of-d-day-marked-at-the-british-normandy-memorial/",
    labelTag: "Main news",
  },
  {
    id: 8,
    title: "Remembrance Commemorations From Across the Nation",
    description: LOREM,
    category: "news",
    type: "audio",
    date: "12 November 2025",
    tags: ["Remembrance", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(8),
    url: "https://www.raf.mod.uk/news/articles/remembrance-commemorations-from-across-the-nation/",
    labelTag: "Main news",
  },
  {
    id: 9,
    title: "RAF Sport Aware Winners 2025",
    description: LOREM,
    category: "news",
    type: "article",
    date: "20 December 2025",
    tags: ["Sport", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(9),
    url: "https://www.raf.mod.uk/news/articles/raf-sport-award-winners-2025/",
    labelTag: "Main news",
  },
  {
    id: 10,
    title: "First Jupiter HC2 takes flight in the UK",
    description: LOREM,
    category: "equipment",
    type: "article",
    date: "17 December 2025",
    tags: ["Aircraft", "Training", "Europe", "Asia", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(10),
    url: "https://www.raf.mod.uk/news/articles/first-jupiter-hc2-takes-flight-in-the-uk/",
    labelTag: "Main news",
  },
  {
    id: 11,
    title: "King's Birthday Honours 2025",
    description: LOREM,
    category: "news",
    type: "article",
    date: "14 June 2025",
    tags: ["Honours", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(11),
    url: "https://www.raf.mod.uk/news/articles/raf-kings-birthday-honours-2025/",
    labelTag: "Main news",
  },
  {
    id: 12,
    title: "Serving Families: On the Move Programme 2025-26 - Armed Forces Covenant Fund",
    description: LOREM,
    category: "news",
    type: "article",
    date: "5 November 2025",
    tags: ["Serving families", "Training", "Reserves", "Cyberspace", "UK", "Community & Support news"],
    imageUrl: PLACEHOLDER_IMG(12),
    url: "https://www.raf.mod.uk/community-support/raf-serving-families-news/serving-families-on-the-move-programme-2025-26-armed-forces-covenant-fund/",
    labelTag: "Community & Support news",
  },
  {
    id: 13,
    title: "RAF Poseidon Maritime Aircraft Build Stronger Ties with Iceland",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "22 January 2026",
    tags: ["International partnerships", "Aircraft", "Protection and Policing", "Maritime patrol", "Europe", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(13),
    url: "https://www.raf.mod.uk/news/articles/raf-poseidon-maritime-aircraft-build-stronger-ties-with-iceland/",
    labelTag: "Main news",
  },
  {
    id: 14,
    title: "Ascension Island Dew Pond Run 2025",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "18 August 2025",
    tags: ["Sport", "Africa", "Station news"],
    imageUrl: PLACEHOLDER_IMG(14),
    url: "https://www.raf.mod.uk/our-organisation/stations/ascension-island-base/news/ascension-island-dew-pond-run-2025/",
    labelTag: "Station news",
  },
  {
    id: 15,
    title: "Supporting our families this summer and beyond",
    description: LOREM,
    category: "news",
    type: "article",
    date: "1 July 2025",
    tags: ["Serving families", "UK", "Community & Support news"],
    imageUrl: PLACEHOLDER_IMG(15),
    url: "https://www.raf.mod.uk/community-support/raf-serving-families-news/supporting-our-families-this-summer-and-beyond/",
    labelTag: "Community & Support news",
    forYou: true,
    themeTag: "Community",
  },
  {
    id: 16,
    title: "Support for those experiencing domestic abuse, sexual violence or stalking",
    description: LOREM,
    category: "news",
    type: "article",
    date: "3 December 2025",
    tags: ["Serving families", "UK", "Community & Support news"],
    imageUrl: PLACEHOLDER_IMG(16),
    url: "https://www.raf.mod.uk/community-support/raf-serving-families-news/support-for-those-experiencing-domestic-abuse-sexual-violence-or-stalking/",
    labelTag: "Community & Support news",
  },
  {
    id: 17,
    title: "The Band of the RAF Regiment serenade Benson community",
    description: LOREM,
    category: "news",
    type: "article",
    date: "9 December 2025",
    tags: ["Serving families", "UK", "Station news"],
    imageUrl: PLACEHOLDER_IMG(17),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-benson/news/the-band-of-the-raf-regiment-serenade-benson-community/",
    labelTag: "Station news",
    forYou: true,
    handle: "@RAFBenson",
  },
  {
    id: 18,
    title: "Flight Sergeant Stephen Curran",
    description: LOREM,
    category: "news",
    type: "article",
    date: "11 November 2025",
    tags: ["Remembrance", "Honours", "Europe", "Asia", "UK", "Station news"],
    imageUrl: PLACEHOLDER_IMG(18),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-boulmer/news/flight-sergeant-steven-curran/",
    labelTag: "Station news",
  },
  {
    id: 19,
    title: "RAF Boulmer and the Air Command and Control Force remembers",
    description: LOREM,
    category: "news",
    type: "article",
    date: "11 November 2025",
    tags: ["Remembrance", "UK", "Station news"],
    imageUrl: PLACEHOLDER_IMG(19),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-boulmer/news/raf-boulmer-and-the-air-command-and-control-force-remembers/",
    labelTag: "Station news",
    forYou: true,
    themeTag: "Remembrance",
  },
  {
    id: 20,
    title: "RAF Falcons use high-tech wind tunnel",
    description: LOREM,
    category: "operations",
    type: "video",
    date: "4 December 2025",
    tags: ["Training", "North America", "Station news"],
    imageUrl: PLACEHOLDER_IMG(20),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-brize-norton/news/raf-falcons-use-high-tech-wind-tunnel/",
    labelTag: "Station news",
  },
  {
    id: 21,
    title: "RAF Brize Norton are the new holders of the prestigious Firmin Sword of Peace",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "7 January 2026",
    tags: ["Humanitarian aid", "Honours", "International partnerships", "Middle East", "UK", "Station news"],
    imageUrl: PLACEHOLDER_IMG(21),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-brize-norton/news/raf-brize-norton-are-the-new-holders-of-the-prestigious-firmin-sword-of-peace/",
    labelTag: "Station news",
    forYou: true,
    themeTag: "Honours",
  },
  {
    id: 22,
    title: "Hurricane pilot and Burma Campaign veteran dies aged 106",
    description: LOREM,
    category: "news",
    type: "article",
    date: "28 December 2025",
    tags: ["Remembrance", "International partnerships", "Europe", "North America", "Asia", "Main news"],
    imageUrl: PLACEHOLDER_IMG(22),
    url: "https://www.raf.mod.uk/news/articles/hurricane-pilot-and-burma-campaign-veteran-dies-aged-106/",
    labelTag: "Main news",
  },
  {
    id: 23,
    title: "Operation Highmast: RAF Concludes Landmark Global Deployment",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "14 January 2026",
    tags: ["International partnerships", "Exercises", "Aircraft", "Europe", "North America", "Middle East", "Asia", "Oceania", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(23),
    url: "https://www.raf.mod.uk/news/articles/operation-highmast-raf-concludes-landmark-global-deployment/",
    labelTag: "Main news",
    forYou: true,
    themeTag: "Operations",
  },
  {
    id: 24,
    title: "Legacy to Lightning: Air Chief Marshal Harv Smyth on How Yesterday's Jets Shape Today's 5th-Gen Tactics",
    description: LOREM,
    category: "equipment",
    type: "video",
    date: "3 November 2025",
    tags: ["International partnerships", "Aircraft", "Senior Leadership", "Team Tempest", "Europe", "Middle East", "Asia", "Oceania", "North America", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(24),
    url: "https://www.raf.mod.uk/news/articles/legacy-to-lightning-air-chief-marshal-harv-smyth-on-how-yesterdays-jets-shape-todays-5th-gen-tactics/",
    labelTag: "Main news",
    forYou: true,
    themeTag: "5th Gen",
  },
  {
    id: 25,
    title: "Exercise Bersama Lima 2025: Strengthening Regional Security through Multilateral Cooperation",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "24 October 2025",
    tags: ["International partnerships", "Exercises", "Space Command", "Asia", "Oceania", "Main news"],
    imageUrl: PLACEHOLDER_IMG(25),
    url: "https://www.raf.mod.uk/news/articles/exercise-bersama-lima-2025-strengthening-regional-security-through-multilateral-cooperation/",
    labelTag: "Main news",
  },
  {
    id: 26,
    title: "RAF marks 85th anniversary of the Battle of Britain",
    description: LOREM,
    category: "news",
    type: "article",
    date: "15 September 2025",
    tags: ["Battle of Britain", "Anniversaries", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(26),
    url: "https://www.raf.mod.uk/news/articles/raf-marks-85th-anniversary-of-battle-of-britain/",
    labelTag: "Main news",
    forYou: true,
    themeTag: "Heritage",
  },
  {
    id: 27,
    title: "RAF Typhoons Benefit From £453m Investment Securing 1,300 British Jobs",
    description: LOREM,
    category: "equipment",
    type: "article",
    date: "19 January 2026",
    tags: ["Aircraft", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(27),
    url: "https://www.raf.mod.uk/news/articles/raf-typhoons-benefit-from-453m-investment-securing-1-300-british-jobs/",
    labelTag: "Main news",
  },
  {
    id: 28,
    title: "Royal Air Force Typhoons Fly First Sortie for Operation Eastern Sentry",
    description: LOREM,
    category: "equipment",
    type: "article",
    date: "16 January 2026",
    tags: ["Aircraft", "International partnerships", "Protection and Policing", "Europe", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(28),
    url: "https://www.raf.mod.uk/news/articles/royal-air-force-typhoons-fly-first-sortie-for-operation-eastern-sentry/",
    labelTag: "Main news",
  },
  {
    id: 29,
    title: "RAF Typhoon FGR4 Aircraft Intercept Multiple Russian Aircraft During Enhanced Air Policing Sortie",
    description: LOREM,
    category: "equipment",
    type: "article",
    date: "13 January 2026",
    tags: ["QRA", "International partnerships", "Protection and Policing", "Aircraft", "Europe", "Main news"],
    imageUrl: PLACEHOLDER_IMG(29),
    url: "https://www.raf.mod.uk/news/articles/raf-typhoon-fgr4-aircraft-intercept-multiple-russian-aircraft-during-enhanced-air-policing-sortie/",
    labelTag: "Main news",
  },
  {
    id: 30,
    title: "RAF St Mawgan Personnel Embark on Educational Visit to Poland",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "6 January 2026",
    tags: ["Remembrance", "Training", "Europe", "Station news"],
    imageUrl: PLACEHOLDER_IMG(30),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-st-mawgan/news/raf-st-mawgan-personnel-embark-on-educational-visit-to-poland/",
    labelTag: "Station news",
  },
  {
    id: 31,
    title: "RAF St Mawgan Hosts Fourth Annual Op CHRISTMAS to Honour Local Veterans",
    description: LOREM,
    category: "news",
    type: "article",
    date: "20 December 2025",
    tags: ["Serving families", "Remembrance", "UK", "Station news"],
    imageUrl: PLACEHOLDER_IMG(31),
    url: "https://www.raf.mod.uk/our-organisation/stations/raf-st-mawgan/news/raf-st-mawgan-hosts-fourth-annual-op-christmas-to-honour-local-veterans/",
    labelTag: "Station news",
    forYou: true,
    themeTag: "Veterans",
  },
  {
    id: 32,
    title: "RAF Typhoons Conduct NATO Air Policing Mission in Estonia",
    description: LOREM,
    category: "operations",
    type: "article",
    date: "21 January 2026",
    tags: ["Protection and Policing", "NATO air policing", "Air policing", "International partnerships", "Europe", "UK", "Main news"],
    imageUrl: PLACEHOLDER_IMG(32),
    url: "https://www.raf.mod.uk/news/articles/",
    labelTag: "Main news",
  },
];

export function getContent(params?: { query?: string; category?: string }): Content[] {
  let items = DUMMY_CONTENT;

  if (params?.query?.trim()) {
    const q = params.query.toLowerCase().trim();
    items = items.filter(
      (item) =>
        item.title.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q) ||
        item.tags?.some((tag) => tag.toLowerCase().includes(q))
    );
  }

  if (params?.category?.trim()) {
    const cat = params.category.toLowerCase().trim();
    items = items.filter((item) => item.category.toLowerCase() === cat);
  }

  return items;
}
